version: '3.8'

services:
  web:
    image: ghcr.io/orakysec/dra-isis-site:latest
    networks:
      - DrIsisNET
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.draisis.rule=Host(`draisisandrade.com`) || Host(`www.draisisandrade.com`)"
        - "traefik.http.routers.draisis.entrypoints=websecure"
        - "traefik.http.routers.draisis.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.draisis.loadbalancer.server.port=80"

networks:
  DrIsisNET:
    external: true
